Web_self_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accountapp.urls'))

]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDetailView.as_view(), name='delete')

    ]

accountapp/models.py
from django.db import models
# Create your models here.



class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.models import HelloWorld


def hello_world(request):
    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list' : hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'   #객체를 html상에서 어떻게 부를 것인지.
    template_name = 'accountapp/detail.html'

class AccountUpdateView(UpdateView):
    model = User
    form_class = UserCreationForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')  # 수정성공 후 다시 되돌아 갈 곳 필요
    template_name = 'accountapp/update.html'

class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/Hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style= "margin: 2rem; text-align: center;" >
        <h1 style = "font-family: 'Roboto Mono', cursive;" class="m-5">
            METHOD</h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
             {# button addons link - Boot strap #}
            <div class="input-group mb-3 w-50 m-auto">
                <input type="text" class="form-control" name="hello_world_input" placeholder="Recipient's username">
                <button class="btn btn-dark" type="submit" id="button-addon2">Button</button>
            </div>

        </form>
        {% if hello_world_list %}

            {% for hello_world in hello_world_list %}
                <h3>{{ hello_world.text }}</h3>
            {% endfor %}

        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}
    <div class = "text-center mw-500 m-auto">
        <div class = "m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action = "{%  url 'accountapp:create' %}" method ="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-5"></div>
                <input type = "submit"
                       class = "btn btn-dark rounded-pill px-5">
            </form>
        </div>
    </div>




{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}


{% block content%}
    <div class = "text-center mw-500 m-auto">
        <div class = "m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action = "{%  url 'accountapp:delete' pk=target_user.pk %}" method ="post">
                {% csrf_token %}
                <div class = "m-5"></div>
                <input type = "submit"
                       class = "btn btn-dark rounded-pill px-5">
            </form>
        </div>
    </div>




{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>{{ target_user.username }}</h4>
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>
        {% if user == target_user %}
        <div>
            <a href= "{% url 'accountapp:update' pk=target_user.pk %}">
            Update Info
            </a> <!--pk 고유값?-->

            <a href= "{% url 'accountapp:delete' pk=target_user.pk %}">
            Quit
            </a> <!--pk 고유값?-->

        </div>
        {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}
    <div class = "text-center mw-500 m-auto">
        <div class = "m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action = "{%  url 'accountapp:login' %}" method ="post">
                {% csrf_token %}
                {%  bootstrap_form form %}
                <div class = "m-5"></div>
                <input type = "submit"
                       class = "btn btn-dark rounded-pill px-5">
        </div>
    </div>




{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content%}
    <div class = "text-center mw-500 m-auto">
        <div class = "m-5">
            <h4>Update info</h4>
        </div>
        <div>
            <form action = "{%  url 'accountapp:update' pk=target_user.pk %}" method ="post"> <!--어떤 주소로 요청을 보낼지-->
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-5"> </div>
                <input type = "submit"
                       class = "btn btn-dark rounded-pill px-5">
            </form>
        </div>
    </div>




{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>

{% include 'header.html' %}

<hr>

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="Engineering_footer_all" >
       <div class="Engineering_footer_1">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스소개</span>
       </div>


</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

{#  boot strap link  #}
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

{#  google font link  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">

{# Static files link #}

{#    <link rel="stylesheet" type = "text/css" href="{% static "base.css" %}">#}
    <link rel="stylesheet" type="text/css"  href="{% static "base.css" %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class= "Engineering_header_all">

    <div class= Engineering_header_1">
        <h1> Data Warehouse </h1>
    </div>

     <div class = "Engineering_header_2">
        {% if not user.is_authenticated%}  <!--로그인 했을시에는 로그아웃,-->

        <span>
            <a href = "{% url 'accountapp:login' %}">
                Log in
            </a>
        </span>
        <span>
            <a href = "{% url 'accountapp:create' %}">
                Sign up
            </a>
        </span>

        {% else %}
        <span>
            <a href = "{% url 'accountapp:detail' pk=user.pk %}">
                My page
            </a>
        </span>
        <span>
            <a href = "{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>
        {% endif %}
    </div>


</div>